name: Deploy AWS RAG Chatbot

on:
  push:
    branches: [main]
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

env:
  AWS_DEFAULT_REGION: eu-central-1
  AWS_BEDROCK_REGION: eu-central-1

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Configure AWS credentials for main deployment
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::767398013018:role/GitHubActions-RAG-Deploy
          role-session-name: GitHubActions-RAG-Deploy-Frankfurt
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          
      - name: Free up disk space
        run: |
          echo "Freeing up disk space..."
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /opt/hostedtoolcache
          sudo apt-get clean
          docker system prune -af --volumes
          df -h
          
      - name: Install dependencies
        run: |
          npm ci
          pip install -r pytest_requirements.txt || echo "No pytest_requirements.txt found"
          
      - name: Build project
        run: |
          echo "Running Amplify codegen and building TypeScript files..."
          npm run build
        
      - name: CDK Bootstrap Frankfurt region
        run: |
          npx cdk bootstrap aws://767398013018/${{ env.AWS_DEFAULT_REGION }}
          
      - name: Configure AWS credentials for Bedrock region
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::767398013018:role/GitHubActions-RAG-Deploy
          role-session-name: GitHubActions-RAG-Deploy-Bedrock
          aws-region: ${{ env.AWS_BEDROCK_REGION }}
          
      - name: CDK Bootstrap Bedrock region (if needed)
        run: |
          npx cdk bootstrap aws://767398013018/${{ env.AWS_BEDROCK_REGION }}
          
      - name: Configure AWS credentials back to main region
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::767398013018:role/GitHubActions-RAG-Deploy
          role-session-name: GitHubActions-RAG-Deploy-Main
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Check and destroy old stack in US East (if exists)
        run: |
          echo "Checking for existing stack in us-east-1..."
          if aws cloudformation describe-stacks --region us-east-1 --stack-name RAG-GenAIChatBotStack 2>/dev/null; then
            echo "Found existing stack in us-east-1. Destroying it first..."
            export CDK_DEFAULT_REGION=us-east-1
            npx cdk destroy RAG-GenAIChatBotStack --force --region us-east-1
            echo "Old stack destroyed successfully"
          else
            echo "No existing stack found in us-east-1, proceeding with deployment"
          fi
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
          
      - name: Deploy CDK Stack in Frankfurt
        run: |
          echo "Deploying new stack in Frankfurt (eu-central-1)..."
          npx cdk deploy --require-approval never --all --concurrency 1 --max-concurrent-resources 10
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
          
      - name: Output deployment info
        run: |
          echo "Deployment completed successfully!"
          echo "Main region: ${{ env.AWS_DEFAULT_REGION }}"
          echo "Bedrock region: ${{ env.AWS_BEDROCK_REGION }}"